<?php

return [
    [
        'key' => 'sales.payment_methods.clover',
        'name' => 'clover::app.configuration.clover',
        'info' => 'clover::app.configuration.clover-info',
        'sort' => 3,
        'fields' => [
            [
                'name' => 'active',
                'title' => 'admin::app.configuration.index.sales.payment-methods.status',
                'type' => 'boolean',
                'validation' => 'required',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'title',
                'title' => 'admin::app.configuration.index.sales.payment-methods.title',
                'type' => 'text',
                'depends' => 'active:1',
                'validation' => 'required_if:active,1',
                'channel_based' => true,
                'locale_based' => true,
            ], [
                'name' => 'description',
                'title' => 'admin::app.configuration.index.sales.payment-methods.description',
                'type' => 'textarea',
                'depends' => 'active:1',
                'channel_based' => true,
                'locale_based' => true,
            ], [
                'name' => 'image',
                'title' => 'admin::app.configuration.index.sales.payment-methods.logo',
                'type' => 'image',
                'info' => 'admin::app.configuration.index.sales.payment-methods.logo-information',
                'depends' => 'active:1',
                'channel_based' => true,
                'locale_based' => false,
                'validation' => 'mimes:bmp,jpeg,jpg,png,webp',
            ], [
                'name' => 'merchant_id',
                'title' => 'clover::app.configuration.merchant-id',
                'type' => 'text',
                'info' => 'admin::app.configuration.index.sales.payment-methods.applicable-production',
                'depends' => 'active:1',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'api_key',
                'title' => 'admin::app.configuration.index.sales.payment-methods.api-key',
                'info' => 'admin::app.configuration.index.sales.payment-methods.applicable-production',
                'type' => 'password',
                'depends' => 'active:1',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'webhook_secret',
                'title' => 'clover::app.configuration.webhook-secret',
                'info' => 'clover::app.configuration.webhook-secret-information',
                'type' => 'password',
                'depends' => 'active:1',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'sandbox',
                'title' => 'admin::app.configuration.index.sales.payment-methods.sandbox',
                'type' => 'boolean',
                'depends' => 'active:1',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'test_merchant_id',
                'title' => 'clover::app.configuration.test-merchant-id',
                'type' => 'text',
                'info' => 'admin::app.configuration.index.sales.payment-methods.applicable-sandbox',
                'depends' => 'active:1',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'api_test_key',
                'title' => 'admin::app.configuration.index.sales.payment-methods.api-test-key',
                'info' => 'admin::app.configuration.index.sales.payment-methods.applicable-sandbox',
                'type' => 'password',
                'depends' => 'active:1',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'test_webhook_secret',
                'title' => 'clover::app.configuration.webhook-secret',
                'info' => 'admin::app.configuration.index.sales.payment-methods.applicable-sandbox',
                'type' => 'password',
                'depends' => 'active:1',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'page_config_uuid',
                'title' => 'clover::app.configuration.page-config-uuid',
                'type' => 'text',
                'depends' => 'active:1',
                'channel_based' => true,
                'locale_based' => false,
            ], [
                'name' => 'sort',
                'title' => 'admin::app.configuration.index.sales.payment-methods.sort-order',
                'type' => 'number',
                'depends' => 'active:1',
                'validation' => 'required_if:active,1|integer|min:1',
                'channel_based' => true,
                'locale_based' => false,
            ],
        ],
    ],
];
